# Generated by Django 5.2.4 on 2025-12-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stocktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('po_complete', 'PO Complete'), ('po_partial', 'PO Partial'), ('po_cancel', 'PO Cancelled')], max_length=100),
        ),
    ]
